'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let algorithms={},result=null,input=null,index=0,playing=null;
const sample={studio:{library:2,cinema:5},library:{cinema:1,park:4},cinema:{park:1},park:{},island:{}};
function stop(){clearInterval(playing);playing=null;$('play').textContent='Play';}
function configure(){stop();const name=$('algorithm').value,meta=algorithms[name];if(!meta)return;$('idea').textContent=meta.idea;$('complexity').textContent=meta.time+' · core algorithm';$('array-inputs').hidden=meta.kind==='graph';$('graph-inputs').hidden=meta.kind!=='graph';$('target-label').hidden=meta.kind!=='search';$('target').required=meta.kind==='search';}
function example(){configure();const name=$('algorithm').value;$('values').value=algorithms[name].kind==='search'?'2, 4, 7, 7, 11, 19':'19, 4, 7, 2, 11, 7';$('target').value=7;$('graph').value=JSON.stringify(name==='bfs'?Object.fromEntries(Object.entries(sample).map(([k,v])=>[k,Object.keys(v)])):sample,null,2);$('start').value='studio';$('end').value='park';}
function arrayState(step){let values=[...input.values];if(result.algorithm==='insertion-sort'&&step?.values)values=step.values;if(result.algorithm==='merge-sort')for(const s of result.steps.slice(0,index))values.splice(s.start,s.length,...s.values);return values;}
function draw(step){
 if(input.graph){
  const names=[...new Set([...Object.keys(input.graph),...Object.values(input.graph).flatMap(v=>Array.isArray(v)?v:Object.keys(v))])],positions=Object.fromEntries(names.map((n,i)=>[n,[220+145*Math.cos(2*Math.PI*i/names.length-Math.PI/2),175+125*Math.sin(2*Math.PI*i/names.length-Math.PI/2)]]));
  const visited=new Set(result.steps.slice(0,index).filter(s=>s.node).map(s=>s.node));
  const edges=Object.entries(input.graph).flatMap(([from,neighbors])=>(Array.isArray(neighbors)?neighbors.map(n=>[n,null]):Object.entries(neighbors)).map(([to,weight])=>{const [x1,y1]=positions[from],[x2,y2]=positions[to],dx=x2-x1,dy=y2-y1,d=Math.hypot(dx,dy)||1;return `<line class="edge" x1="${x1+dx/d*16}" y1="${y1+dy/d*16}" x2="${x2-dx/d*20}" y2="${y2-dy/d*20}" marker-end="url(#arrow)"/>${weight===null?'':`<text class="edge-label" x="${(x1+x2)/2+5}" y="${(y1+y2)/2-5}">${esc(weight)}</text>`}`;})).join('');
  $('visual').innerHTML=`<svg viewBox="0 0 440 350" role="img" aria-label="Directed graph; highlighted node is the current step"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="#887868"/></marker></defs>${edges}${names.map(n=>{const [x,y]=positions[n];return `<circle class="node ${visited.has(n)?'visited':''} ${step?.node===n||step?.to===n?'current':''}" cx="${x}" cy="${y}" r="16"/><text class="node-label" x="${x}" y="${y+32}">${esc(n)}</text>`;}).join('')}</svg>`;
  $('legend').textContent='Arrows show direction. Burgundy marks the current node or improved destination; rose marks expanded nodes. The exact state below explains the update.';
 }else{
  const values=arrayState(step),largest=Math.max(1,...values.map(Math.abs));
  $('visual').innerHTML='<div class="bars">'+values.map((v,i)=>`<div class="bar ${i===(step?.middle??step?.index??step?.inserted_at)?'active':''} ${step?.left!==undefined&&(i<step.left||i>step.right)?'outside':''}"><b>${values.length<=24?esc(v):''}</b><span>${values.length<=24?i:''}</span></div>`).join('')+'</div>';
  $('visual').querySelectorAll('.bar').forEach((b,i)=>{b.style.height=(Math.abs(values[i])/largest*130+8)+'px';b.title=`Index ${i}: ${values[i]}`;});
  $('legend').textContent='Bar height shows magnitude (absolute value); labels show signed values and zero-based indexes. Burgundy marks the active index; faded bars are outside binary search’s current interval.';
 }
}
function show(){if(!result)return;const step=index?result.steps[index-1]:null;$('position').textContent=`${index} / ${result.steps.length}`;$('step').value=index;$('explanation').textContent=step?.explanation||'Initial input. Advance to see the first operation.';$('state').textContent=JSON.stringify(step||input,null,2);$('back').disabled=index===0;$('forward').disabled=index===result.steps.length;$('play').disabled=!result.steps.length;$('rewind').disabled=index===0;draw(step);}
$('inputs').onsubmit=async event=>{event.preventDefault();stop();$('error').textContent='';$('run').disabled=true;try{const name=$('algorithm').value,meta=algorithms[name];const payload={algorithm:name};if(meta.kind==='graph'){payload.graph=JSON.parse($('graph').value);payload.start=$('start').value.trim();payload.end=$('end').value.trim();}else{const raw=$('values').value.trim();payload.values=raw.startsWith('[')?JSON.parse(raw):raw?raw.split(/[\s,]+/).map(Number):[];if(payload.values.some(v=>typeof v!=='number'||!Number.isFinite(v)))throw new Error('Enter finite numbers.');if(meta.kind==='search')payload.target=Number($('target').value);}
 const response=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error);result=data;input=payload;index=0;$('step').max=result.steps.length;$('step').disabled=!result.steps.length;$('answer').textContent=JSON.stringify(result.output,null,2);$('metrics').innerHTML=Object.entries(result.metrics).map(([name,value])=>`<span><strong>${value}</strong>${esc(name)}</span>`).join('');$('trace-note').textContent=result.trace_truncated?'Trace was capped at 500 steps; the full computation still completed.':'Full trace recorded. Complexity excludes validation and trace storage.';$('export').disabled=false;show();}catch(error){$('error').textContent=error.message;}finally{$('run').disabled=false;}};
$('algorithm').onchange=example;$('example').onclick=example;$('step').oninput=()=>{stop();index=Number($('step').value);show();};$('back').onclick=()=>{stop();index=Math.max(0,index-1);show();};$('forward').onclick=()=>{stop();index=Math.min(result.steps.length,index+1);show();};$('rewind').onclick=()=>{stop();index=0;show();};$('play').onclick=()=>{if(playing){stop();return;}if(index===result.steps.length)index=0;$('play').textContent='Pause';playing=setInterval(()=>{index++;show();if(index>=result.steps.length)stop();},Number($('speed').value));};$('speed').onchange=stop;
$('export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({version:1,input,result},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='algorithm-run.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
fetch('/api/algorithms').then(r=>r.json()).then(data=>{algorithms=data;example();}).catch(()=>$('error').textContent='The local lab is unavailable. Restart the server and reload.');
